### ISSUE TITLE
[Spell][Class] Summon Gargoyle

### ISSUE THREAD

**Issue by klankin** [Stormforge-gg/Bugtracker-Wotlk-Beta#140]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Gargoyle is melee attacking

**Current behaviour**: When interrupted, the gargoyle will start auto attacking. Also while free casting, the gargoyle will occasionally stop to auto attack twice before continuing to cast again (if the target is in melee range)

**Expected behaviour**: The gargoyle should not be auto attacking, it is a caster minion.

**Revision**: 1041

**Comment by Wolffenstein** [comment]
Fixed in rev 1042.

**Comment by haephaistoss** [comment]
"Gargoyle is one of the only cooldowns available as an unholy death knight which makes it that much more important, and when your main cooldown loses a large amount of damage due to it using its melee attacks on the target, it can be detrimental to your overall dps. Fortunately, there is a way to avoid your gargoyle from being summoned in melee range which allows it to cast freely and reach its fullest potential with no loss to your own personal dps.

When you actually summon the gargoyle, you will notice it is actually flown down about 10-15 yards in front of you. SO, if you were to turn around 180 degrees and summon it then, it will actually fly down a good distance behind you, and since you should be behind the boss in the first place, this puts it at a perfect ranged position far from melee range. I have personally tested this several times and in each case it hasn't used a single melee attack on the target."

forrás: https://web.archive.org/web/20100808075715/http://elitistjerks.com/f72/t72364-unholy_dps_3_3_5_only_exception/p102/
