### ISSUE TITLE
[Adding Injury to Insult] [Howling Fjord]

### ISSUE THREAD

**Issue by QuadrozZz** [Stormforge-gg/Bugtracker-Wotlk-Beta#21]
https://www.wowhead.com/quest=12481
If Npc https://www.wowhead.com/npc=24458 and https://www.wowhead.com/npc=24474 kill Npc https://www.wowhead.com/npc=24238 will not counted for you but should be.
Npc https://www.wowhead.com/npc=24458 and https://www.wowhead.com/npc=24474 should help you kill elite quest Npc https://www.wowhead.com/npc=24238.

ps. Quest are doable without Npc's. But will very hard/impossible to do it alone without help.

**Comment by Evolvee** [comment]
Probably because the NPCs caused more than 50% of dmg taken to the quest credit NPC - which makes it not count for the player.

Need proof of this being incorrect behavior.

**Comment by FX-SF** [comment]
Test 1: Use scroll, run to ambush area, perform no damage to boss: Could not leash mob all the way to ambush site without mob resetting (distance is too long).
Test 2: Use scroll, run halfway to ambush area, use scroll again, perform no damage to boss. Was able to leash boss to ambush area (was forced targeting me due to scroll effect), mobs finished off boss, no damage done by player. Receive no credit.
Test 3: Use scroll, Solo kill boss without ambush. Used Beta buffs and killed, got credit.
Test 4: Use scroll, deal 20% damage to boss, run to ambush site, allow mobs to finish off. Did not receive credit.
Test 5: Use scroll, let boss get to 70% through "thorns" style buff only (i.e. ret aura). Boss reset itself?? Occured while i was standing still after 30 seconds.
Test 6: Yada yada, boss 55%, use ambush, no credit.
Test 7: Use scroll, get mob to 45%, let ambush finish off boss... **Suprisingly didnt get credit!!** (did i possibly fuck up/miscalc?)
Test 8: Attempt test 7 again, but with picture evidence (see pictures below)
Test 9: yada yada, got boss to 37%, used ambush, no credit. (beginning to suspect it is last hit? will test more)

A) Used scroll on Boss
![WoWScrnShot_050622_165234](https://user-images.githubusercontent.com/105084838/167228948-8daeae3e-2b44-4e90-8e5e-748960633293.jpg)
B) Gain partial credit and begin run to ambush site
![WoWScrnShot_050622_165238](https://user-images.githubusercontent.com/105084838/167228951-664f7cf7-adc1-4aa6-964e-0dc333354750.jpg)
C) 3 seconds before taunt wore off, stopped and began damage on Boss to avoid reset of leash
![WoWScrnShot_050622_165256](https://user-images.githubusercontent.com/105084838/167228957-ce92fe07-3662-4dea-8b85-26276cbe5692.jpg)
D) Damaged Boss to 49% (lucky! Did majority of damage on Boss)
![WoWScrnShot_050622_165307](https://user-images.githubusercontent.com/105084838/167229091-6c79dcec-cb81-4a33-80c1-1477056776e5.jpg)
E) Shows final damage on Boss (ambush NPC's delivered final blow, credited me for the slay, but whatever?) Did not receive credit. (NPC's MIGHT have actually done majority damage if we count overkill damage done to Boss, all this is very technical, I don't know, but just possible theories)
![WoWScrnShot_050622_165401](https://user-images.githubusercontent.com/105084838/167228967-530ccab2-0889-41d7-bcc8-2c26add7633c.jpg)
:

**Comment by Evolvee** [comment]
fixed in next rev
