### ISSUE TITLE
[Quest] The last Line of Defense

### ISSUE THREAD

**Issue by Blimsquge** [Stormforge-gg/Bugtracker-Wotlk-Beta#23]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:  When inside the Argent Cannon, the kill range seems to be really small. Also, when inside the Argent Cannon and the Frostbrood Destroyer, destroyed the cannon I was in, the screen went red and all I could see was me parachuting. This has only happened once for the first cannon I was in which was the very north cannon or the far right. https://www.wowhead.com/spell=57385/argent-cannon

**Current behaviour**: 

**Expected behaviour**: 

**Revision**:

**Comment by Peglaa** [comment]
Making the kill range larger effectively stops you from being able to kill the Frostrbrood Destroyers that fly in to attack you since the attacks will just go thru them. Maybe there is a sweet spot of like 60-70y range but I dunno, we tried 100y but you just cant kill the Destroyers before they destroy your cannon.
