### ISSUE TITLE
Stealth and mobs that see you 

### ISSUE THREAD

**Issue by NatsumeLily** [Stormforge-gg/Bugtracker-Wotlk-Beta#289]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: When in stealth, mobs can spot you while in stealth.

**Current behaviour**: If you get spotted while in stealth and get far enough away from the mob before they hit you, they reset. 

**Expected behaviour**: Mobs that spot you in stealth should keep that "aggro" even if you get get far enough away and don't get stealth removed with damage. 

**Revision**:

**Comment by Vishiswaz** [comment]
To be specific, he's not talking about the regular leash distance, he's talking about the distance a mob can start seeing stealthies at.

So, to be clear:

Mob X can see Player 1 in stealth at distance A.

Mob X aggros to Player 1, Player 1 runs away.

Before Player 1 gets to the regular, long leash distance where the mob would reset, once the distance between Mob X and Player 1 exceeds distance A, the mob resets.

We can tell this isn't regular leashing because it happens in instances where there is no leash effect, and mobs should not reset after they've been aggro'd no matter how far they've been kited, stealth or no stealth, unless a Vanish or mage Invisibility or hunter Feign Death (or nelf Shadowform?) is used.

**Comment by Emtec** [comment]
Fixed in 1126
