### ISSUE TITLE
[NPC] Scarlet Commander Mograine

### ISSUE THREAD

**Issue by KurtySuit** [Stormforge-gg/Bugtracker-Wotlk-Beta#309]
**Description**: 
[Scarlet Commander Mograine](https://classic.wowhead.com/npc=3976/scarlet-commander-mograine) doesn't use his [Divine Shield](https://classic.wowhead.com/spell=642/divine-shield)

**Current behaviour**:
doesn't use his divine shield

**Expected behaviour**: 
Use Divine Shield when low life

**Revision**:

**Comment by FX-SF** [comment]
Conclusion: I believe Expected behavior was changed from no ability to cast Divine Shield to the ability to cast Divine Shield @ 25%, from Vanilla Wow to Classic Wow respectively. There are other spells that he does not seem to use like lay of hands and hammer of judgement

1) Current Behavior confirmed, did not use Divine Shield during a 2 minute fight with him at various HP levels. 
2) In this first video from 4 years ago:
https://www.youtube.com/watch?v=vehCRinBbrs&ab_channel=SoupaSoka,
You can see Mograine casting Divine Shield twice, each time at 25%. 
3) In this second video from 14 years ago:
https://www.youtube.com/watch?v=D94sGkokhvA&ab_channel=hyshnari,
You can see Mograine dropping below 25% twice without being killed, yet never once casts Divine Shield (I think). 
4) My untested theory is that Vanilla WoW's Mograine does not use Divine Shield, while Classic WoW's Mograine does use Divine Shield (at 25% hp each time)

**Comment by KurtySuit** [comment]
He uses Hammer of Justice, make sure to delevel to avoid resist

**Comment by Wolffenstein** [comment]
Fixed in rev 1294.
