### ISSUE TITLE
[Cone of Cold][Mage]

### ISSUE THREAD

**Issue by Abovexx** [Stormforge-gg/Bugtracker-Wotlk-Beta#40]
**Description**:  Does not apply 70% movement slow effect.

**Current behaviour**: Does not apply 70% movement slow effect. But does apply 50% movement slow effect.

**Expected behaviour**:  Targets in a cone in front of the caster take 774 to 847 Frost damage and are slowed by 70%

**Revision**:

**Comment by Gn0m** [comment]
https://wotlkdb.com/?talent#oZZV00h 
![image](https://user-images.githubusercontent.com/40593874/162495218-910f8c5f-f391-462a-b469-b07a331a30f9.png)
checked with another priest, the slowdown works correctly without talent and with talent, the only mistake is the display, the debuff itself is written incorrectly, i.e. 30-40-50 without talent and 40-50-60 with talent, but it should be 40 -50-60 without talent and 50-60-70 with talent

**Comment by haephaistoss** [comment]
/run print(GetUnitSpeed("target") / 7 * 100)
/script x=GetUnitSpeed("player") DEFAULT_CHAT_FRAME:AddMessage(format("Speed: %d yds/sec, %.1f kph, %.1f mph, %d%% normal run speed",x,x*3600/1093.6133,x*45/22,x/7*100))


use this to check actualy movement speed, tooltips don't update in wotlk client

**Comment by Gn0m** [comment]
tested with this script, the speed reduction is correct, with or without talent, but the display of numbers in the debuff on the target is not correct, it goes to -10%, i.e. if it should be with 70% talent it shows 60%, if without talent 60% shows 50% and so with all 3 abilities, ice shield, ice arrow and cone of cold

**Comment by haephaistoss** [comment]
you can't do it. Tooltips can't update in wotlk. No need to report this, because it's how the game works.

Your game client has no idea if the enemy has a talent or not, so it can't update either.

**Comment by Gn0m** [comment]
I tested it again, I saw what you wrote about, thanks for such a patient explanation

**Comment by haephaistoss** [comment]
Same with shields, the client has no idea about the amount of absorb a given shield provides, the server doesn't tell your game this info. Thus making addons that tell you exactly what shield amounts you have and recalculates them every time you take dmg is extremely difficult, because you need to do all the maths by hand within the addon, and read combat log and then subtract the dmg and so on.

And all this gives you numbers you can actually work with only if server side the shield is correct otherwise you're fucked.
